//about
$(document).ready(function(){
    $('.box1').mouseenter(function(){
        $('.bi-shop').addClass('text-green'),
        $('.body1').removeClass('border-secondary'),
        $('.body1').addClass('border-green')
    }),
    $('.box1').mouseleave(function(){
        $('.bi-shop').removeClass('text-green'),
        $('.body1').removeClass('border-green'),
        $('.body1').addClass('border-secondary')
    }),
    $('.box2').mouseenter(function(){
        $('.bi-bag-check-fill').addClass('text-green'),
        $('.body2').removeClass('border-secondary'),
        $('.body2').addClass('border-green')
    }),
    $('.box2').mouseleave(function(){
        $('.bi-bag-check-fill').removeClass('text-green'),
        $('.body2').removeClass('border-green'),
        $('.body2').addClass('border-secondary')
    }),
    $('.box3').mouseenter(function(){
        $('.bi-headset').addClass('text-green'),
        $('.body3').removeClass('border-secondary'),
        $('.body3').addClass('border-green')
    }),
    $('.box3').mouseleave(function(){
        $('.bi-headset').removeClass('text-green'),
        $('.body3').removeClass('border-green'),
        $('.body3').addClass('border-secondary')
    }),
    $('.box4').mouseenter(function(){
        $('.bi-slack').addClass('text-green'),
        $('.body4').removeClass('border-secondary'),
        $('.body4').addClass('border-green')
    }),
    $('.box4').mouseleave(function(){
        $('.bi-slack').removeClass('text-green'),
        $('.body4').removeClass('border-green'),
        $('.body4').addClass('border-secondary')
    })
})
//Team
$(document).ready(function(){
    $('.img1-team').mouseenter(function(){
        $('.over-img1-team').fadeTo(1000,0.5);
    }),
    $('.img1-team').mouseleave(function(){
        $('.over-img1-team').fadeTo(1000,0);
    }),
    $('.img2-team').mouseenter(function(){
        $('.over-img2-team').fadeTo(1000,0.5);
    }),
    $('.img2-team').mouseleave(function(){
        $('.over-img2-team').fadeTo(1000,0);
    }),
    $('.img3-team').mouseenter(function(){
        $('.over-img3-team').fadeTo(1000,0.5);
    }),
    $('.img3-team').mouseleave(function(){
        $('.over-img3-team').fadeTo(1000,0);
    }),
    $('.img4-team').mouseenter(function(){
        $('.over-img4-team').fadeTo(1000,0.5);
    }),
    $('.img4-team').mouseleave(function(){
        $('.over-img4-team').fadeTo(1000,0);
    }),
    $('.img5-team').mouseenter(function(){
        $('.over-img5-team').fadeTo(1000,0.5);
    }),
    $('.img5-team').mouseleave(function(){
        $('.over-img5-team').fadeTo(1000,0);
    }),
    $('.img6-team').mouseenter(function(){
        $('.over-img6-team').fadeTo(1000,0.5);
    }),
    $('.img6-team').mouseleave(function(){
        $('.over-img6-team').fadeTo(1000,0);
    })
})
//process
$(document).ready(function(){
    $('.card1-process').mouseenter(function(){
        $(this).removeClass('shadow-lg'),
        $(this).addClass('shadow-lg1');
    }),
    $('.card1-process').mouseleave(function(){
        $(this).removeClass('shadow-lg1'),
        $(this).addClass('shadow-lg');
    }),
    $('.card2-process').mouseenter(function(){
        $(this).removeClass('shadow-lg'),
        $(this).addClass('shadow-lg1');
    }),
    $('.card2-process').mouseleave(function(){
        $(this).removeClass('shadow-lg1'),
        $(this).addClass('shadow-lg');
    }),
    $('.card3-process').mouseenter(function(){
        $(this).removeClass('shadow-lg'),
        $(this).addClass('shadow-lg1');
    }),
    $('.card3-process').mouseleave(function(){
        $(this).removeClass('shadow-lg1'),
        $(this).addClass('shadow-lg');
    })
})
//work
$(document).ready(function(){
    $('.img1-work').mouseenter(function(){
        $('.over-img1-work').fadeTo('fast',0.7);
    }),
    $('.img1-work').mouseleave(function(){
        $('.over-img1-work').fadeTo('fast',0);
    }),
    $('.img2-work').mouseenter(function(){
        $('.over-img2-work').fadeTo('fast',0.7);
    }),
    $('.img2-work').mouseleave(function(){
        $('.over-img2-work').fadeTo('fast',0);
    }),
    $('.img3-work').mouseenter(function(){
        $('.over-img3-work').fadeTo('fast',0.7);
    }),
    $('.img3-work').mouseleave(function(){
        $('.over-img3-work').fadeTo('fast',0);
    }),
    $('.img4-work').mouseenter(function(){
        $('.over-img4-work').fadeTo('fast',0.7);
    }),
    $('.img4-work').mouseleave(function(){
        $('.over-img4-work').fadeTo('fast',0);
    }),
    $('.img5-work').mouseenter(function(){
        $('.over-img5-work').fadeTo('fast',0.7);
    }),
    $('.img5-work').mouseleave(function(){
        $('.over-img5-work').fadeTo('fast',0);
    }),
    $('.img6-work').mouseenter(function(){
        $('.over-img6-work').fadeTo('fast',0.7);
    }),
    $('.img6-work').mouseleave(function(){
        $('.over-img6-work').fadeTo('fast',0);
    })
})
